# This name is shown in the status badge in the README
name: build

on: [push, pull_request]

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 15]
        bouncy_castle: [true, false]

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run tests
      run: USE_BOUNCY_CASTLE=${{matrix.bouncy_castle}} ./gradlew cleanTest check

    - name: Archive test report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: "*/build/reports/**"

    - name: Build JavaDoc
      run: ./gradlew assembleJavadoc
