name: test

on:
  push:
    branches:
      - '*'
      - '!master'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
      - '!master'
    tags:
      - '*'

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 13]

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run tests
      run: ./gradlew check

    - name: Build JavaDoc
      run: ./gradlew assembleJavadoc
